name: qda
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.20.1
  - ipython=8.8.0
  - jedi=0.18.2
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.1.3
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.6.2
  - ply=3.11
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.14.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7
  - pywin32=227
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - statsmodels=0.13.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.8.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.6
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.8
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
